spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/accounts/**

server:
  port: ${SERVER_PORT:9000}
